#!/usr/bin/env ruby

require 'json'
require 'shellwords'

CONFIG_PATH = ARGV[0] || "/etc/idfly-deploy"

def _get_config()
  config = JSON.parse(File.read(CONFIG_PATH), {symbolize_names: true})

  Dir.foreach('/home') { |dir|
    if dir[0] == '.'
      next
    end

    path = File.join('/', 'home', dir, 'deploy.conf')
    if !File.exist?(path)
      next
    end
    
    begin
      local_config = JSON.parse(File.read(path), {symbolize_names: true})
    rescue => error
      puts("Failed to read config #{path}", error.to_s())
    end

    dir_sym = dir.to_sym()
    if config[:sites][dir_sym].nil?()
      config[:sites][dir_sym] = {user: dir_sym}
    end

    site_config = config[:sites][dir_sym]
    [:name, :url, :message, :path, :exec].each() { |key|
      if local_config.has_key?(key)
        site_config[key] = local_config[key]
      end
    }
  }

  return config
end

def deploy(key)
  key = key.to_sym()
  sites = _get_config()[:sites]
  if !sites.has_key?(key)
    STDERR.puts("Site \"#{key}\" not exists")
    return
  end

  site = sites[key]
  Dir.chdir(site[:path]) {
    deploy_site(site)
    update_redmine_repositories()
    send_slack_notification(site)
  }
end

def deploy_site(site)
  _run_command('sudo', '-u', site[:user], 'git', 'pull')
  puts("Site \"#{site[:name]}\" were deployed")

  if site.has_key?(:exec)
    exec = site[:exec]
    if !exec.instance_of?(::Array)
      exec = [exec]
    end

    exec.each() { |command|
      _run_command('sudo', '-u', site[:user], 'bash', '-c', command)
    }
  end
end

def update_redmine_repositories()
  config = _get_config()[:redmine]
  if config.nil?()
    return
  end

  url =
    "#{config[:url]}/sys/fetch_changesets" +
    "?key=#{config[:api_key]}"

  _run_command('wget', url, '-qO', '/dev/null')
end

def send_slack_notification(site)
  config = _get_config()[:slack]
  if config.nil?()
    return
  end

  url = site[:slack_webhook_url] || config[:webhook_url]
  if !url
    return
  end


  text = ''

  matches = (`git log --oneline | head -n 1` || '').match(/#(\d+)/)
  if matches
    redmine_url = _get_config()[:redmine][:url] rescue nil
    text = "<#{redmine_url}/issues/#{matches[1]}|##{matches[1]}>"
  end

  if text.empty?()
    text = "#{site[:name]}"
  else
    text += " (#{site[:name]})"
  end

  text += " выгружен#{matches && 'а'} на #{site[:url]}"

  message = config[:message].
    merge(site[:slack_message] || {}).
    merge({'text' => text})

  encoded_message = JSON.dump(message)
  _run_command('wget', '--post-data', encoded_message, url, '-qO', '/dev/null')
end

def _run_command(*args)
  command = Shellwords.join([*args])

  puts(command)
  system(command)
end

# web server

require 'rack'

app = Proc.new do |env|
  req = Rack::Request.new(env)
  site = req.params['site']
  puts("-" * 80)
  puts("#{DateTime.now().to_s()}: deployment of #{site}")
  puts("-" * 80)
  deploy(site)
  ['200', {'Content-Type' => 'text/html'}, ['OK']]
end

Rack::Handler::WEBrick.run(app, _get_config()[:server] || {})
